# Generated by Django 4.1.1 on 2022-09-08 14:54

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('digits', '0001_initial'),
    ]

    operations = [
    ]
