# Generated by Django 4.1.1 on 2022-09-20 10:12

from django.db import migrations, models
import ndarraydjango.fields
import numpy


class Migration(migrations.Migration):

    dependencies = [
        ('digits', '0002_digits'),
    ]

    operations = [
        migrations.AddField(
            model_name='digit',
            name='label',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='digit',
            name='picture',
            field=ndarraydjango.fields.NDArrayField(dtype=numpy.float64, editable=True, shape=(784, 1)),
        ),
    ]
