# Generated by Django 4.1.1 on 2022-09-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digits', '0003_digit_label_alter_digit_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='digit',
            name='isTrainingDigit',
            field=models.BooleanField(default=True),
        ),
    ]
