# Generated by Django 4.1.1 on 2022-09-24 06:50

from django.db import migrations
import sys
import os
from django.conf import settings

sys.path.insert(1, os.path.join(settings.BASE_DIR, 'digits/neural_network/data'))
import data_loader


def export_data(apps, schema_editor):
    training_data, validation_data, test_data = data_loader.load_data()
    sets = (training_data, validation_data, test_data)
    for i, data_set in enumerate(sets):
        isTrain = True if i == 0 else False
        for picture, label in zip(data_set[0], data_set[1]):
            Digit = apps.get_model('digits', 'Digit')
            Digit(picture=picture, label=label, isTrainingDigit=isTrain).save()


class Migration(migrations.Migration):
    dependencies = [
        ('digits', '0003_digit_label_alter_digit_picture'),
    ]

    operations = [
        migrations.RunPython(export_data),
    ]
