# Generated by Django 4.1.1 on 2022-09-24 12:07

from django.db import migrations
import sys
import os
import json
from django.conf import settings
import numpy as np


def export_model(apps, schema_editor):

    with open(settings.MODEL, 'r') as f:
        data = json.load(f)

    ModelState = apps.get_model('digits', 'ModelState')
    ModelState(biases=json.dumps(data['biases']),
               weights=json.dumps(data['weights']),
               train_accuracy=data['training_accuracy'][-1],
               test_accuracy=data['evaluation_accuracy'][-1],
               retrain_in=10).save()


class Migration(migrations.Migration):

    dependencies = [
        ('digits', '0007_alter_modelstate_biases_alter_modelstate_weights'),
    ]

    operations = [
        migrations.RunPython(export_model)
    ]
