# Generated by Django 4.1.1 on 2022-09-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digits', '0008_digits2'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelstate',
            name='is_training',
            field=models.BooleanField(default=False),
        ),
    ]
